<?php

/**
 * Implementation of hook_menu().
 */
function wysiwyg_msoffice_detector_menu() {
	$items = array();

	// Add a local task under the general WYSIWYG settings
	$items['admin/settings/wysiwyg/msoffice_detector'] = array(
		'title' => 'MS Office Detector',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wysiwyg_msoffice_detector_admin_settings_form'),
		'description' => 'Configure how the editor should react when detecting Microsoft Office content.',
		'access arguments' => array('administer filters'),
		'type' => MENU_LOCAL_TASK
	);
	
	return $items;
}

/**
 * Implementation of hook_form_form_id_alter().
 */
function wysiwyg_msoffice_detector_form_wysiwyg_profile_form_alter(&$form, &$form_state) {
	if (variable_get('wysiwyg_msoffice_detector_profile_config', 0)) {
		$profile = $form['#parameters'][2];
	
		// Add an option to enable/disable MS Office detection
		$form['output']['msoffice_detect'] = array(
			'#type' => 'checkbox',
			'#title' => t('Detect copy/paste from Microsoft Office'),
			'#default_value' => ($profile && isset($profile->settings['msoffice_detect'])) ? $profile->settings['msoffice_detect'] : 0,
			'#return_value' => 1,
			'#description' => t('If enabled the editor will try to detect content which has been copy/pasted from Microsoft Office and act according to the configuration'),
		);
	}
}

function wysiwyg_msoffice_detector_wysiwyg_editor_settings_alter(&$settings, $context) {	
	if (!variable_get('wysiwyg_msoffice_detector_profile_config', 0) || 
			$context['profile']->settings['msoffice_detect']) {
		if (!$js_added) {
			drupal_add_js(drupal_get_path('module', 'wysiwyg_msoffice_detector') . '/js/wysiwyg_msoffice_detector.js', 'module');
			$js_added = 1;
		}
		
		$wmd_config = variable_get('wysiwyg_msoffice_detector_default', array('reaction' => 1, 'message' => t('It seems like you have copy/pasted content from Microsoft Office into a WYSIWYG field. This may prevent the content from displaying correctly. Do you wish to proceed?')));

		// Add the settings to the global configuration
		drupal_add_js(array('WysiwygMsOfficeDetector' => $wmd_config), 'setting');
		
		// Add the settings to the editor for future reference
		$settings['msoffice_detect'] = $wmd_config;
	}
}

/**
 * Admin settings form
 */
function wysiwyg_msoffice_detector_admin_settings_form($form_state) {
	
	$form['wysiwyg_msoffice_detector_profile_config'] = array(
		'#type' => 'checkbox',
		'#title' => t('Configure individual WYSIWYG profiles'),
		'#description' => t('Enable configuration for individual profiles. If disabled each profile will use the default configuration.'),
		'#default_value' => variable_get('wysiwyg_msoffice_detector_profile_config', 0),
		'#return_value' => 1,
	);

	$form['wysiwyg_msoffice_detector_default'] = array(
		'#type' => 'fieldset',
		'#title' => 'Default',
		'#description' => 'Configuration across WYSIWYG profiles',
		'#tree' => true,
	);
	
	$wmd_config = variable_get('wysiwyg_msoffice_detector_default', array('reaction' => 1, 'message' => t('It seems like you have copy/pasted content from Microsoft Office into a WYSIWYG field. This may prevent the content from displaying correctly. Do you wish to proceed?')));
	
	$form['wysiwyg_msoffice_detector_default']['reaction'] = array(
		'#type' => 'radios',
		'#title' => t('Reaction'),
		'#description' => t('What should happen if content copy/pasted from Microsoft Office is detected?'),
		'#default_value' => $wmd_config['reaction'],
		'#options' => array(1 => t('Ask for confirmation when saving content'),
												2 => t('Prevent the user from saving content'),
									),
	);
	
	$form['wysiwyg_msoffice_detector_default']['message'] = array(
		'#type' => 'textarea',
		'#title' => t('Message'),
		'#description' => t('The message to display to the user'),
		'#default_value' => $wmd_config['message'],
	);
	
	return system_settings_form($form);
}